export const site = {
  baseUrl: "https://mcasos.github.io/cv-portafolio",
  github: "https://github.com/mcasos",
  name: "Miguel André Casós Torre",
  email: "miguel.casos@hotmail.com",
  location: { es: "Lima, Perú", en: "Lima, Peru" },
  role: {
    es: "Desarrollador Full-stack especializado en IA local, automatización y datos",
    en: "Full-stack Developer specializing in local AI, automation, and data",
  },
  summary: {
    es: "Diseño productos que no solo funcionan: explican sus decisiones, conservan evidencia y hacen visibles sus límites. Desarrollo full-stack, IA local, automatización y datos.",
    en: "I design products that do more than work: they explain their decisions, preserve evidence, and make their boundaries visible. Full-stack development, local AI, automation, and data.",
  },
  education: {
    degree: { es: "Ingeniería de Software", en: "Software Engineering" },
    institution: "Universidad Peruana de Ciencias Aplicadas (UPC)",
    dates: { es: "2022 — Actualidad", en: "2022 — Present" },
  },
  skills: [
    { title: { es: "Producto e IA", en: "Product & AI" }, items: ["Next.js / React / TypeScript", "FastAPI / Python 3.12", { es: "LLM locales / RAG", en: "Local LLMs / RAG" }, { es: "APIs tipadas", en: "Typed APIs" }] },
    { title: { es: "Datos", en: "Data" }, items: ["Power BI / DAX", "Excel", { es: "Modelado relacional", en: "Relational modeling" }, "Data quality"] },
    { title: { es: "Automatización", en: "Automation" }, items: ["n8n", "IMAP + Telegram / WhatsApp", { es: "OCR local", en: "Local OCR" }, { es: "Workflows auditables", en: "Auditable workflows" }] },
    { title: { es: "Calidad", en: "Quality" }, items: ["pytest / Vitest", "Ruff / mypy", "ESLint / TypeScript", { es: "CI y documentación", en: "CI and documentation" }] },
  ],
};

export const labels = {
  es: {
    nav: ["Inicio", "Habilidades", "Educación", "Proyectos", "Certificaciones", "Contacto"],
    skip: "Saltar al contenido",
    navigation: "Navegación principal",
    index: "Índice",
    hello: "Hola, soy",
    stack: "Stack",
    skills: "Habilidades",
    education: "Educación",
    projects: "Proyectos",
    built: "Productos con evidencia",
    featured: "Principales",
    support: "Complementarios",
    certifications: "Certificaciones verificables",
    credentials: "Formación complementaria",
    verify: "Verificar",
    certificate: "Certificado PDF",
    see: "Ver caso",
    code: "Ver código",
    contact: "Contacto",
    contactTitle: "Construyamos algo útil",
    contactBody: "Disponible para oportunidades full-stack, IA local, automatización y datos en Lima o remoto.",
    github: "GitHub",
    cv: "Descargar CV",
    back: "Volver al portafolio",
    problem: "Problema",
    solution: "Solución",
    evidence: "Evidencia",
    quality: "Calidad",
    architecture: "Flujo",
    footer: "Construido con HTML, CSS y JavaScript generado desde contenido bilingüe.",
    pageTitle: "Full-stack, IA local, automatización y datos",
    heroClaim: "Construyo sistemas que pueden demostrar por qué confiar en ellos.",
    heroNote: "Producto · Ingeniería · Evidencia",
    sectionIntro: "Cada caso separa lo construido, lo medido y lo que todavía no debe afirmarse.",
    summaryLabel: "Resumen verificable",
    summaryCases: "casos documentados",
    summaryCandidate: "candidato de producción",
    summaryLanguages: "contenido equivalente",
    summaryLimits: "pruebas aprobadas",
    caseStudy: "Caso de estudio",
    contextTitle: "Contexto operativo",
    approachTitle: "Enfoque aplicado",
    productResults: "Producto y resultados",
    verifiedScope: "Alcance verificado",
    flowInput: "Entrada",
    flowInputBody: "Datos controlados y explícitos",
    flowDomain: "Dominio",
    flowDomainBody: "Reglas y validación desacopladas",
    flowOutput: "Salida",
    flowOutputBody: "Resultado trazable",
    notFoundTitle: "Página no encontrada",
    notFoundBody: "La dirección no existe o cambió. Puedes volver al portafolio o abrir su versión en inglés.",
    notFoundHome: "Volver al inicio",
    notFoundEnglish: "Open English version",
  },
  en: {
    nav: ["Home", "Skills", "Education", "Projects", "Certifications", "Contact"],
    skip: "Skip to content",
    navigation: "Main navigation",
    index: "Index",
    hello: "Hello, I'm",
    stack: "Stack",
    skills: "Skills",
    education: "Education",
    projects: "Projects",
    built: "Products backed by evidence",
    featured: "Featured",
    support: "Supporting",
    certifications: "Verifiable certifications",
    credentials: "Additional learning",
    verify: "Verify",
    certificate: "Certificate PDF",
    see: "View case study",
    code: "View source",
    contact: "Contact",
    contactTitle: "Let's build something useful",
    contactBody: "Open to full-stack, local AI, automation, and data opportunities in Lima or remote.",
    github: "GitHub",
    cv: "Download résumé",
    back: "Back to portfolio",
    problem: "Problem",
    solution: "Solution",
    evidence: "Evidence",
    quality: "Quality",
    architecture: "Flow",
    footer: "Built with HTML, CSS, and JavaScript generated from bilingual content.",
    pageTitle: "Full-stack, local AI, automation, and data",
    heroClaim: "I build systems that can show you why they deserve trust.",
    heroNote: "Product · Engineering · Evidence",
    sectionIntro: "Each case separates what was built, what was measured, and what should not yet be claimed.",
    summaryLabel: "Verifiable summary",
    summaryCases: "documented cases",
    summaryCandidate: "production candidate",
    summaryLanguages: "equivalent content",
    summaryLimits: "passing tests",
    caseStudy: "Case study",
    contextTitle: "Operational context",
    approachTitle: "Applied approach",
    productResults: "Product and results",
    verifiedScope: "Verified scope",
    flowInput: "Input",
    flowInputBody: "Controlled, explicit data",
    flowDomain: "Domain",
    flowDomainBody: "Decoupled rules and validation",
    flowOutput: "Output",
    flowOutputBody: "Traceable result",
    notFoundTitle: "Page not found",
    notFoundBody: "This address does not exist or has changed. Return to the portfolio or open its Spanish version.",
    notFoundHome: "Back to home",
    notFoundEnglish: "Abrir versión en español",
  },
};

export const certifications = [
  {
    issuer: "IBM",
    title: "Generative AI Fundamentals",
    detail: { es: "Especialización de 5 cursos", en: "5-course specialization" },
    date: { es: "Julio 2026", en: "July 2026" },
    dateIso: "2026-07",
    verifyUrl: "https://coursera.org/verify/specialization/2RJF9QA0LA96",
    file: "downloads/certifications/ibm-generative-ai-fundamentals.pdf",
  },
  {
    issuer: "University of Michigan",
    title: "Capstone: Retrieving, Processing, and Visualizing Data with Python",
    detail: { es: "Curso con proyecto final", en: "Capstone course" },
    date: { es: "Marzo 2026", en: "March 2026" },
    dateIso: "2026-03",
    verifyUrl: "https://coursera.org/verify/U19YI7WOQ2H9",
    file: "downloads/certifications/python-data-capstone.pdf",
  },
  {
    issuer: "Google",
    title: "Connect and Protect: Networks and Network Security",
    detail: { es: "Ciberseguridad de redes", en: "Network cybersecurity" },
    date: { es: "Julio 2026", en: "July 2026" },
    dateIso: "2026-07",
    verifyUrl: "https://coursera.org/verify/HDP32Y7H6NI4",
    file: "downloads/certifications/google-connect-protect.pdf",
  },
  {
    issuer: "Google",
    title: "Tools of the Trade: Linux and SQL",
    detail: { es: "Linux y consultas SQL", en: "Linux and SQL queries" },
    date: { es: "Julio 2026", en: "July 2026" },
    dateIso: "2026-07",
    verifyUrl: "https://coursera.org/verify/KK9Y7BDL4F1B",
    file: "downloads/certifications/google-linux-sql.pdf",
  },
  {
    issuer: "Google",
    title: "Automate Cybersecurity Tasks with Python",
    detail: { es: "Automatización aplicada a ciberseguridad", en: "Cybersecurity automation" },
    date: { es: "Julio 2026", en: "July 2026" },
    dateIso: "2026-07",
    verifyUrl: "https://coursera.org/verify/YPMHTGM6ES76",
    file: "downloads/certifications/google-automate-cybersecurity-python.pdf",
  },
];

export const projects = [
  {
    slug: "localforge-ai-lab", icon: "LF", primary: true, flagship: true,
    title: "LocalForge AI Lab",
    repoUrl: "https://github.com/mcasos/localforge-ai-lab",
    category: { es: "Caso insignia · IA local", en: "Flagship case · Local AI" },
    summary: { es: "Laboratorio privado para evaluar modelos locales, recomendar el mejor para cada tarea y consultar documentos con RAG y citas verificables.", en: "A private lab for evaluating local models, recommending the best fit for each task, and querying documents through RAG with verifiable citations." },
    tech: ["Next.js", "TypeScript", "FastAPI", "Python", "LM Studio", "RAG", "Playwright"],
    features: {
      es: ["Benchmarks versionados con fallos retenidos", "Smart Router con decisión explicable", "RAG privado con citas y borrado verificado", "Frontera local validada en Windows"],
      en: ["Versioned benchmarks with retained failures", "Smart Router with explainable decisions", "Private RAG with citations and verified deletion", "Local boundary validated on Windows"],
    },
    metrics: [["131", { es: "pruebas API", en: "API tests" }], ["20/20", { es: "intentos de soak", en: "soak attempts" }], ["6", { es: "pruebas E2E", en: "E2E checks" }], ["0.88%", { es: "crecimiento VRAM", en: "VRAM growth" }]],
    problem: { es: "Elegir un modelo local por popularidad oculta diferencias de calidad, latencia, confiabilidad y consumo; además, una interfaz de chat común no demuestra privacidad ni trazabilidad.", en: "Choosing a local model by popularity hides differences in quality, latency, reliability, and resource use; a generic chat UI also fails to prove privacy or traceability." },
    solution: { es: "Construí una plataforma local-first que registra cada ejecución, normaliza métricas y fallos, filtra capacidades antes de puntuar y explica por qué recomienda o descarta un modelo. En RAG separa respuesta, citas y afirmaciones sin respaldo.", en: "I built a local-first platform that records every run, normalizes metrics and failures, filters capabilities before scoring, and explains why a model is recommended or rejected. Its RAG flow separates the answer, citations, and unsupported claims." },
    quality: { es: "Candidato local v1.0.0-rc.1: 131 pytest, 15 Vitest, 26 pruebas de scripts, 6 E2E, smoke y reinicio aprobados. Un soak de 30.07 minutos completó 20/20 intentos sin fallos ni bloqueos.", en: "Local candidate v1.0.0-rc.1: 131 pytest, 15 Vitest, 26 script tests, 6 E2E checks, smoke, and restart passed. A 30.07-minute soak completed 20/20 attempts with no failures or stuck runs." },
    status: { es: "RC local verificado · repositorio público", en: "Verified local RC · public repository" },
    gallery: [
      ["assets/projects/localforge/overview.png", { es: "Superficie general del laboratorio", en: "Lab overview" }],
      ["assets/projects/localforge/smart-router.png", { es: "Router de modelos con criterios explícitos", en: "Model router with explicit criteria" }],
      ["assets/projects/localforge/private-rag.png", { es: "RAG local con respuestas fundamentadas", en: "Local RAG with grounded answers" }],
    ],
  },
  {
    slug: "rutafactura", icon: "RF", primary: true,
    title: "RutaFactura",
    repoUrl: "https://github.com/mcasos/rutafactura",
    category: { es: "Proyecto principal · Full-stack", en: "Featured project · Full-stack" },
    summary: { es: "MVP para preparar, revisar y emitir de forma simulada facturas de transporte, con OCR local, expediente digital, cobranza y auditoría.", en: "An MVP for preparing, reviewing, and simulating transport invoice issuance, with local OCR, digital records, collections, and audit trails." },
    tech: ["Next.js", "TypeScript", "Prisma", "SQLite", "OCR", "Vitest"],
    features: {
      es: ["OCR local con confirmación humana", "Cálculos monetarios exactos", "Modo piloto seguro y auditable", "SUNAT claramente identificado como simulación"],
      en: ["Local OCR with human confirmation", "Exact monetary calculations", "Secure and auditable pilot mode", "SUNAT clearly identified as a simulation"],
    },
    metrics: [["453", { es: "pruebas aprobadas", en: "passing tests" }], ["89", { es: "archivos de prueba", en: "test files" }], ["16", { es: "migraciones", en: "migrations" }], ["5", { es: "pasos guiados", en: "guided steps" }]],
    problem: { es: "La facturación de transporte combina guías, tickets, viajes, crédito y reglas por cliente. Sin una sola fuente de verdad, los errores se multiplican.", en: "Transport invoicing combines shipping documents, weight tickets, trips, credit terms, and customer rules. Without a single source of truth, errors multiply." },
    solution: { es: "El sistema procesa documentos localmente, exige revisar los datos detectados, conserva versiones y registra cada cambio. Los importes usan enteros para evitar errores de punto flotante.", en: "The system processes documents locally, requires review of detected data, preserves versions, and logs every change. Amounts use integer arithmetic to avoid floating-point errors." },
    quality: { es: "Typecheck, lint, 453 pruebas y build de producción aprobados; 3 pruebas dependientes del entorno permanecen omitidas. No incluye identidad tributaria real ni emisión SUNAT productiva.", en: "Type checking, linting, 453 tests, and the production build passed; 3 environment-dependent tests remain skipped. It includes no real tax identity or production SUNAT issuance." },
    status: { es: "Repositorio público · SUNAT simulado", en: "Public repository · simulated SUNAT integration" },
    gallery: [
      ["assets/projects/rutafactura/dashboard.png", { es: "Dashboard por empresa emisora", en: "Dashboard by issuing company" }],
      ["assets/projects/rutafactura/flujo-guiado.png", { es: "Flujo guiado de preparación", en: "Guided preparation flow" }],
      ["assets/projects/rutafactura/bandeja-sunat.png", { es: "Bandeja SUNAT en modo de prueba", en: "SUNAT inbox in test mode" }],
    ],
  },
  {
    slug: "reporte-energ", icon: "BI", primary: true,
    title: "ReporteEnerg",
    category: { es: "Proyecto principal · Analítica", en: "Featured project · Analytics" },
    summary: { es: "Dashboard ejecutivo para analizar operación, demanda, calidad y eventos energéticos mediante Power BI y un libro Excel complementario.", en: "An executive dashboard for analyzing energy operations, demand, quality, and events through Power BI and a complementary Excel workbook." },
    tech: ["Power BI", "DAX", "Power Query", "Excel", "KPIs"],
    features: { es: ["Modelo de datos y medidas DAX", "Narrativa ejecutiva en siete páginas", "Análisis técnico y control de calidad", "Entregables PBIX y Excel"], en: ["Data model and DAX measures", "Seven-page executive narrative", "Technical analysis and quality control", "PBIX and Excel deliverables"] },
    metrics: [["7", { es: "páginas", en: "pages" }], ["3", { es: "vistas públicas", en: "public views" }], ["2", { es: "entregables", en: "deliverables" }], ["0", { es: "datos personales", en: "personal records" }]],
    problem: { es: "Los indicadores energéticos pierden valor cuando la demanda, la calidad y los eventos se revisan por separado.", en: "Energy indicators lose value when demand, quality, and events are reviewed separately." },
    solution: { es: "Un modelo integrado conecta las métricas técnicas con una lectura ejecutiva, permitiendo detectar tendencias, anomalías y prioridades operativas.", en: "An integrated model connects technical metrics to an executive view, making trends, anomalies, and operational priorities easier to identify." },
    quality: { es: "PBIX válido con siete páginas, modelo preservado, datos simulados y una anomalía de calidad documentada y excluida de los indicadores.", en: "Valid seven-page PBIX, preserved model, simulated data, and one documented data-quality anomaly excluded from the indicators." },
    downloads: [["downloads/reporte-energ/ReporteEnerg_PowerBI_Final.pbix", "PBIX"], ["downloads/reporte-energ/ReporteEnerg_Portafolio_Final.xlsx", "Excel"], ["downloads/reporte-energ/README.md", "Metodología / Methodology"]],
    gallery: [
      ["assets/projects/reporte-energ/resumen-ejecutivo.png", { es: "Resumen ejecutivo", en: "Executive summary" }],
      ["assets/projects/reporte-energ/operacion-y-demanda.png", { es: "Operación y demanda", en: "Operations and demand" }],
      ["assets/projects/reporte-energ/calidad-y-eventos.png", { es: "Calidad y eventos", en: "Quality and events" }],
    ],
  },
  {
    slug: "vuelafacil", icon: "VF", primary: true,
    title: "VuelaFácil Familia",
    repoUrl: "https://github.com/mcasos/vuelafacil-familia",
    category: { es: "Proyecto principal · Python", en: "Featured project · Python" },
    summary: { es: "Aplicación de escritorio que compara vuelos y calcula el costo familiar real sin mezclar monedas ni transformar datos desconocidos en certezas.", en: "A desktop application that compares flights and calculates the real family cost without mixing currencies or turning unknown data into false certainty." },
    tech: ["Python", "Tkinter", "pytest", "Ruff", "mypy", "Excel"],
    features: { es: ["Dominio monetario con Decimal", "Proveedores desacoplados", "Modo mock reproducible", "Exportación trazable a Excel"], en: ["Decimal-based money domain", "Decoupled providers", "Reproducible mock mode", "Traceable Excel exports"] },
    metrics: [["243", { es: "pruebas aprobadas", en: "passing tests" }], ["7", { es: "pruebas omitidas", en: "skipped tests" }], ["42", { es: "archivos tipados", en: "typed source files" }], ["0", { es: "credenciales en demo", en: "demo credentials" }]],
    problem: { es: "Comparar vuelos familiares requiere equipaje, alcance del precio, monedas y datos incompletos; ordenar solo por tarifa conduce a decisiones erróneas.", en: "Comparing family flights requires handling baggage, price scope, currencies, and incomplete data; sorting only by fare leads to poor decisions." },
    solution: { es: "La lógica separa proveedores, dominio y presentación. Los valores desconocidos permanecen explícitos y el ranking evita comparar cantidades incompatibles.", en: "The architecture separates providers, domain logic, and presentation. Unknown values remain explicit, and ranking avoids comparing incompatible amounts." },
    quality: { es: "243 pruebas, Ruff y mypy aprobados. La evidencia visual se añadirá cuando Tcl/Tk funcione correctamente en el entorno de captura.", en: "243 tests, Ruff, and mypy passed. Visual evidence will be added once Tcl/Tk works correctly in the capture environment." },
    status: { es: "Repositorio público · modo mock reproducible", en: "Public repository · reproducible mock mode" },
  },
  {
    slug: "control-alojamiento", icon: "CA", primary: false,
    title: "Control de Alojamiento",
    repoUrl: "https://github.com/mcasos/control-alojamiento",
    category: { es: "Proyecto complementario · Full-stack", en: "Supporting project · Full-stack" },
    summary: { es: "Panel móvil para administrar estancias, cobranza, caja y cierre diario con persistencia local y sincronización opcional.", en: "A mobile-first dashboard for stays, collections, cash management, and daily close with local persistence and optional synchronization." },
    tech: ["Next.js", "TypeScript", "Supabase", "Zod", "Vitest"],
    features: { es: ["Modos mensual y hospedaje simple", "Operación móvil primero", "Fallback local", "Supabase opcional"], en: ["Monthly and short-stay modes", "Mobile-first operation", "Local fallback", "Optional Supabase sync"] },
    metrics: [["28", { es: "pruebas aprobadas", en: "passing tests" }], ["8", { es: "archivos de prueba", en: "test files" }], ["6", { es: "rutas compiladas", en: "compiled routes" }], ["2", { es: "modos operativos", en: "operating modes" }]],
    problem: { es: "La información dispersa dificulta conocer ocupación, pagos pendientes y consistencia de caja.", en: "Scattered information makes it difficult to track occupancy, pending payments, and cash consistency." },
    solution: { es: "La interfaz prioriza tareas diarias y desacopla dominio, persistencia y seguridad. Puede operar localmente y sincronizar con Supabase cuando está configurado.", en: "The interface prioritizes daily tasks and separates domain, persistence, and security. It can work locally and sync with Supabase when configured." },
    quality: { es: "28 pruebas, lint, typecheck y build aprobados con datos ficticios.", en: "28 tests, linting, type checking, and the production build passed using fictional data." },
    status: { es: "Repositorio público · Supabase opcional", en: "Public repository · optional Supabase sync" },
    gallery: [["assets/projects/control-alojamiento/dashboard.png", { es: "Panel operativo móvil", en: "Mobile operations dashboard" }]],
  },
  {
    slug: "n8n-automatizaciones", icon: "n8", primary: false,
    title: "Alertas multicanal con n8n",
    category: { es: "Proyecto complementario · Automatización", en: "Supporting project · Automation" },
    summary: { es: "Tres workflows que detectan correos relevantes, estructuran el mensaje y envían alertas por Telegram o WhatsApp.", en: "Three workflows that detect relevant emails, structure the message, and send alerts through Telegram or WhatsApp." },
    tech: ["n8n", "IMAP", "Telegram API", "WhatsApp API"],
    features: { es: ["Entrada IMAP", "Filtro y formato reutilizable", "Tres canales de salida", "Reintentos controlados sin credenciales"], en: ["IMAP input", "Reusable filtering and formatting", "Three output channels", "Controlled retries without credentials"] },
    metrics: [["3", { es: "workflows", en: "workflows" }], ["9", { es: "nodos", en: "nodes" }], ["0", { es: "conexiones rotas", en: "broken connections" }], ["0", { es: "secretos", en: "secrets" }]],
    problem: { es: "Los correos importantes pueden perderse entre mensajes rutinarios y requieren seguimiento manual.", en: "Important emails can be lost among routine messages and require manual follow-up." },
    solution: { es: "Un núcleo IMAP filtra y normaliza cada alerta antes de enviarla a Telegram, WhatsAble o Meta WhatsApp Cloud.", en: "An IMAP core filters and normalizes each alert before sending it to Telegram, WhatsAble, or Meta WhatsApp Cloud." },
    quality: { es: "Los tres JSON se parsean, están desactivados, no contienen credenciales, no tienen conexiones rotas y aplican tres intentos a cada salida. La ejecución real requiere cuentas propias.", en: "All three JSON files parse, are disabled, contain no credentials, have no broken connections, and apply three attempts to each outbound action. Live execution requires the user's own accounts." },
    downloads: [["downloads/n8n/n8n-email-telegram-workflow.json", "Telegram JSON"], ["downloads/n8n/n8n-email-whatsable-workflow.json", "WhatsAble JSON"], ["downloads/n8n/n8n-email-whatsapp-cloud-workflow.json", "WhatsApp Cloud JSON"]],
  },
];
